<?xml version="1.0"?>

<package format="2">

  <name>figure_eight_planner</name>

  <version>0.0.1</version>

  <description>
    Chinese Formula Student Driverless Bazi Closed Loop System
  </description>


  <maintainer email="your@email.com">
    bazi_team
  </maintainer>


  <license>MIT</license>


  <buildtool_depend>catkin</buildtool_depend>


  <depend>rospy</depend>
  <depend>mapping</depend>

  <depend>std_msgs</depend>

  <depend>geometry_msgs</depend>

  <depend>nav_msgs</depend>

  <depend>sensor_msgs</depend>

  <depend>visualization_msgs</depend>

  <depend>tf</depend>


</package>
